# Generated by Django 4.1.1 on 2022-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='image',
            field=models.ImageField(null=True, upload_to='account/image'),
        ),
    ]
