# Generated by Django 4.1.1 on 2022-09-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auser',
            old_name='image',
            new_name='picture',
        ),
    ]
